#!/bin/bash
clear
trap '' 2
dialog --clear --backtitle "Debian MATE Installation Type" --title "Choose Installation type:" --menu "Please select:" 10 45 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
# OK is pressed
if [ "$?" = "0" ]
then
        _return=$(cat temp)
 
        # Minimal is selected
        if [ "$_return" = "1" ]
        then
      		echo 'Installing Minimal System '
	  	sleep 4
    		apt-get install mate-desktop-environment-core mate-terminal tightvncserver -y
		dpkg --configure -a
		apt-get chromium -yy
		sed -i 's/chromium %U/chromium --no-sandbox %U/g' /usr/share/applications/chromium.desktop
        fi
 
         # Full is selected
        if [ "$_return" = "2" ]
        then
             echo 'Installing Full System '
	     sleep 4
             apt-get install mate-desktop-environment-core mate-terminal tightvncserver xfe gimp neofetch libreoffice task-mate-desktop -y
	     dpkg --configure -a
	     apt-get chromium -yy
		sed -i 's/chromium %U/chromium --no-sandbox %U/g' /usr/share/applications/chromium.desktop
        fi
 # Cancel is pressed
else
        echo "Cancel is pressed, Restarting The Menu......"
	sleep 3
	dialog --menu "Choose Installation type:" 10 40 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
fi
 
# remove the temp file
rm -f temp
trap 2
apt-get clean
