#!/bin/bash
clear
trap '' 2
dialog --clear --backtitle "Debian i3WM Installation" --title "Choose Installation type:" --menu "Please select:" 10 45 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
# OK is pressed
if [ "$?" = "0" ]; then
  _return=$(cat temp)

  # Minimal is selected
  if [ "$_return" = "1" ]; then
    echo 'Installing Minimal System '
    sleep 4
    apt install i3 tigervnc-standalone-server wget nano dbus-x11 xorg xterm xfce4-terminal pcmanfm shotwell feh cairo-dock libexo-1-0 tigervnc-common --no-install-recommends -y
  fi

  # Full is selected
  if [ "$_return" = "2" ]; then
    echo 'Installing Full System '
    sleep 4
    apt install i3 tigervnc-standalone-server wget nano dbus-x11 xorg xterm xfce4-terminal pcmanfm shotwell feh cairo-dock libexo-1-0 tigervnc-common firefox-esr gimp neofetch libreoffice lightdm libreoffice-gtk synaptic vlc xdg-utils xorg xserver-xorg-input-all xserver-xorg-video-all -y
  fi
  # Cancel is pressed
else
  echo "Cancel is pressed, Restarting The Menu......"
  sleep 3
  dialog --menu "Choose Installation type:" 10 40 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
fi

# remove the temp file
rm -f temp
trap 2
apt-get clean
